# Generated by Django 5.0.7 on 2024-08-18 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_user_name_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_name',
        ),
        migrations.DeleteModel(
            name='Files',
        ),
    ]
