# Generated by Django 5.0.7 on 2024-08-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_users_user_name_delete_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_name',
            field=models.CharField(default='marcos', max_length=255),
            preserve_default=False,
        ),
    ]
