# Generated by Django 5.0.7 on 2024-08-19 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='pdf_file',
            field=models.FileField(default='jeje', upload_to='pdfs/'),
            preserve_default=False,
        ),
    ]
