# Generated by Django 5.0.7 on 2024-08-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_files_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='pages',
            field=models.IntegerField(editable=False),
        ),
    ]
