# Generated by Django 5.0.7 on 2024-09-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_file_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='pages',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
